version: "3"
services:
  agent:
    image: grafana/agent:latest
    restart: always
#    ports:
#      - 8428:8428
#      - 4318:4318
#      - 4317:4317
#      - 12345:12345
    volumes:
      - "./agent.yml:/etc/agent-config/agent.yaml:ro"
      - "/:/host/root:ro"
      - "/sys:/host/sys:ro"
      - "/proc:/host/proc:ro"
      - "/tmp/agent:/etc/agent"
    command: [
    "-config.file=/etc/agent-config/agent.yaml",
    "-server.http.address=0.0.0.0:12345",
    "-server.grpc.address=0.0.0.0:12346",
    ]
    network_mode: host
    pid: "host"