- name: deploy-grafana-agent
  hosts: grafana
  become: yes
  tasks:
  - name: Validando instalação do docker.
    become: yes
    package:
      name: docker.io
      state: present

  - name: Baixando a imagem do grafana-agent
    docker_image:
      name: grafana/agent:latest
      source: pull

  - name: Executando o grafana agent
    #  - name: Parando qualquer versão do grafana-agent antiga.
    #    docker_container:
    #      name: grafana_agent
    #      state: stopped
    #      remove: yes

    docker_container:
      name: grafana_agent
      image: grafana/agent:latest
      state: started
      restart_policy: always
      #      ports:
      #      - "8428:8428"
      #      - "4318:4318"
      #      - "4317:4317"
      #      - "12345:12345"
      volumes:
      - "./agent.yml:/etc/agent-config/agent.yaml:ro"
      - "/:/host/root:ro"
      - "/sys:/host/sys:ro"
      - "/proc:/host/proc:ro"
      - "/tmp/agent:/etc/agent"
      command:
      - "-config.file=/etc/agent-config/agent.yaml"
      - "-server.http.address=0.0.0.0:12345"
      - "-server.grpc.address=0.0.0.0:12346"
      network_mode: host
      pid_mode: "host"
